---
- name: Install slurm-wlm package.
  ansible.bultin.apt:
    name: slurm-wlm
    state: present
    update_cache: true


- name: Install slurmdbd package.
  ansible.bultin.apt:
    name: slurmdbd
    state: present
    update_cache: true
  when: 2 in install_code_list