---
# 1=compute, 2=database, 3=controller, 4=first controller, 5=all
- name: Make sure epel-release is installed.
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_distribution|lower == 'centos'


# does this make it permamently?
- name: Exclude slurm in epel repo.
  ansible.builtin.yum_repository:
    name: epel-release
    exclude: slurm*
  when: ansible_distribution|lower == 'centos'