---
- name: Install mariaDB on CentOS 7.
  ansible.builtin.yum:
    name:
      - "mariadb-server"
      - "mariadb-devel"
      - "MySQL-python"
    state: present
    update_cache: true
  when: ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('7', '==')


- name: Install mariaDB on CentOS 8.
  block:
    - name: Install mariaDB on CentOS 8.
      ansible.builtin.yum:
        name:
          - "mariadb-server"
          - "mariadb-devel"
        state: present
        update_cache: true
    
    - name: Install python3-mysql for CentOS 8.
      ansible.builtin.dnf:
        name: "python3-mysql"
        state: present
        update_cache: true
  when: ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('8', '==')


- name: Install mariaDB on Ubuntu 20.
  ansible.builtin.apt:
    name:
      - "mariadb-server"
      - "libmariadbclient-dev"
      - "libmariadb-dev"
      - "python3-mysqldb"
    state: present
    update_cache: true
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '==')