---
- name: Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against CentOS 7 and 8 or Ubuntu 20. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: (ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('7', '<')) or
        (ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('8', '>')) or
        (ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '!='))

- name: "Check OS version and family"
  ansible.builtin.debug:
    msg: "PASS | This role can only be executed on CentOS 7 and 8 and Ubuntu 20 operating systems"
  when: (ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('7', '==')) or
        (ansible_distribution|lower == 'centos' and ansible_distribution_major_version is version_compare('8', '==')) or
        (ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '=='))


- name: Check if munge key host is defined when install code 4 is not given.
  ansible.builtin.fail:
    msg: "This installation was not identified as first controller and needs a given munge key host. "
  when: 4 not in install_code_list and munge_key_host is not defined


- name: Check if slurm_controller_hostname and slurm_controller_ip are given when install code is not 4.
  ansible.builtin.fail:
    msg: "slurm_controller_hostname and slurm_controller_ip have to specified if not installing as controller. "
  when: 
    - 4 not in install_code_list and slurm_controller_hostname is not defined
    - 4 not in install_code_list and slurm_controller_ip is not defined


- name: Set slurm_controller_hostname and slurm_controller_ip when install code is 4.
  ansible.builtin.set_fact:
    slurm_controller_hostname: "{{ ansible_hostname }}"
    slurm_controller_ip: "{{ ansible_facts.default_ipv4.address }}"
  when: 4 in install_code_list


- name: Check if slurm_database_hostname is given when install code is not 2.
  ansible.builtin.fail:
    msg: "slurm_database_hostname has to specified if not installing as database. "
  when: 
    - 2 not in install_code_list and slurm_database_hostname is not defined


- name: Set slurm_database_hostname when install code is 2.
  ansible.builtin.set_fact:
    slurm_database_hostname: "{{ ansible_hostname }}"
  when: 2 in install_code_list


# todo for mariadb only if not installed
- name: Check if mariadb_root_password and mariadb_slurm_password are given when install code is 2.
  ansible.builtin.fail:
    msg: "mariadb_root_password and mariadb_slurm_password have to be specified when installing as database. "
  when: 
    - 2 in install_code_list and mariadb_root_password is not defined
    - 2 in install_code_list and mariadb_slurm_password is not defined


- name: Set cluster_name to cryocluster when not specified.
  ansible.builtin.set_fact:
    cluster_name: "cryocluster"
  when: cluster_name is not defined and 4 in install_code_list


- name: Set slurm_version to cryocluster when not specified.
  ansible.builtin.set_fact:
    slurm_version: 20.11.8
  when: slurm_version is not defined