---
- name: Add munge group
  ansible.builtin.group:
    name: munge
    gid: 1005
    state: present
    system: false

- name: Add munge user
  ansible.builtin.user:
    name: munge
    uid: 1005
    group: munge
    create_home: true
    home: "/var/lib/munge"
    shell: "/sbin/nologin "
    state: present
    system: false


- name: Add slurm group
  ansible.builtin.group:
    name: slurm
    gid: 1006
    state: present
    system: false

- name: Add slurm user
  ansible.builtin.user:
    name: slurm
    uid: 1006
    group: slurm
    create_home: true
    home: "/var/lib/slurm"
    shell: "/bin/bash "
    state: present
    system: false


- name: Make sure epel-release is installed.
  ansible.builtin.yum:
    name: epel-release
    state: present


- name: Install munge dependencies.
  ansible.builtin.yum:
    name:
      - "OpenSSL"
      - "bzip2"
      - "zlib"
      - "pkgconf"


- name: Create munge directories.
  block: 
  - name: Create and set permissions for /etc/munge
    ansible.builtin.file:
      path: /etc/munge
      state: directory
      recurse: true
      owner: munge
      group: munge
      mode: 0700
  
  - name: Create and set permissions for /var/lib/munge
  ansible.builtin.file:
    path: /var/lib/munge
    state: directory
    recurse: true
    owner: munge
    group: munge
    mode: 0700
  
- name: Create and set permissions for /var/log/munge
  ansible.builtin.file:
    path: /var/log/munge
    state: directory
    recurse: true
    owner: munge
    group: munge
    mode: 0700

- name: Create and set permissions for /run/munge # var/run/munge?
  ansible.builtin.file:
    path: /run/munge
    state: directory
    recurse: true
    owner: munge
    group: munge
    mode: 0755
    

- name: Install munge, munge-libs, munge-devel
  ansible.builtin.yum:
    name:
      - "munge"
      - "munge-libs"
      - "munge-devel"
    state: present
    update_cache: true


- name: Create munge key.
  ansible.builtin.shell: /usr/sbin/create-munge-key -r
  become_user: munge
  when: inventory_hostname in groups['slurmcontroller']


- name: Copy kefile to other nodes.
  ansible.posix.synchronize:
    src: /etc/munge/munge.key
    dest: /etc/munge/munge.key
    mode: push
  delegate_to: "{{ groups['slurmcontroller'][0] }}"
  when: inventory_hostname not in groups['slurmcontroller']


- name: Make sure munge key file correct permissions.
  ansible.builtin.file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0600


- name: Enable munge
  ansible.builtin.systemd:
    name: munge
    state: started
    enabled: true


# does this make it permamently?
- name: Exclude slurm in epel repo.
  ansible.builtin.yum_repository:
    name: epel-release
    exclude: slurm*


- name: Install slurm prerequisites.
  ansibel.builtin.yum:
    name:
      - "hwloc-devel" # for cgroup Task Affinity Plugin
      - "hdf5-devel" # for HDF5 Job Profiling Plugin
      - "man2html" # for HTML Man Pages Plugin
      - "freeipmi-devel" # for IPMI Energy Consumtion Plugin
      - "libibmad-devel" # for InfiniBand Accounting Plugin
      - "libibumad-devel" # for InfiniBand Accounting Plugin
      - "lua-devel" # for Lua Support Plugin
      - "mysql-devel" # for MySQL Plugin
      - "pam-devel" # for PAM Support Plugin
      - "numactl-devel" # for NUMA Affinity Plugin
      - "readline-devel" # for Readline Support Plugin
      - "rrdtool-devel" # for RRD External Sensor Data Collection Plugin
      - "gtk2-devel" # for sview Plugin
      - "rpm-build"
      - "gcc"
      - "openssl"
      - "openssl-devel"
      - "ncurses-devel"
      - "perl-Switch"
      - "perl-ExtUtils-MakeMaker"
      - "xorg-x11-xauth"
      - "libssh2-devel"
      - "http-parser-devel" # for Slurm REST API
      - "libyaml-devel" # for Slurm REST API
      - "json-c-devel" # for Slurm REST API
      - "libjwt-devel" # for Slurm REST API
    state: present
    update_cache: true


# setup mariadb path
- name: Install mariaDB for slurm
  ansible.builtin.yum:
    name:
      - "mariadb-server"
      - "mariadb-devel"
    state: present
    update_cache: true
  when: inventory_hostname in groups['slurmdatabasehost']


