---
# i could just use ufw for both? but most would have firewalld on redhat bases i guess
# default ipv4 is not good practice i guess
- name: Make sure firewalld is installed.
  ansible.builtin.package:
    name: firewalld
    state: present
  when: ansible_distribution|lower == 'centos'


- name: Make sure ufw is installed.
  ansible.builtin.apt:
    name: ufw
    state: present
  when: ansible_distribution|lower == 'ubuntu'


- name: Make sure firewalld is started and enabled.
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
  when: ansible_distribution|lower == 'centos'


- name: Make sure ufw is started and enabled.
  ansible.builtin.systemd:
    name: ufw
    state: started
    enabled: true
  when: ansible_distribution|lower == 'ubuntu'


- name: Setup firewalld.
  ansible.posix.firewalld:
    zone: trusted
    interface: "{{ ansible_facts.default_ipv4.interface }}"
    permanent: true
    immediate: true
    enabled: true
  when: ansible_distribution|lower == 'centos'


- name: Setup ufw.
  community.general.ufw:
    interface: "{{ ansible_facts.default_ipv4.interface }}"
    enabled: true
    policy: allow
  when: ansible_distribution|lower == 'ubuntu'