---
- name: Add munge group
  ansible.builtin.group:
    name: munge
    gid: "{{ munge_gid }}"
    state: present
    system: false

- name: Add munge user
  ansible.builtin.user:
    name: munge
    uid: "{{ munge_uid }}"
    group: munge
    create_home: true
    home: "{{ munge_home }}"
    shell: "/sbin/nologin "
    state: present
    system: false


- name: Add slurm group
  ansible.builtin.group:
    name: slurm
    gid: "{{ slurm_gid }}"
    state: present
    system: false

- name: Add slurm user
  ansible.builtin.user:
    name: slurm
    uid: "{{ slurm_uid }}"
    group: slurm
    create_home: true
    home: "{{ slurm_home }}"
    shell: "/bin/bash "
    state: present
    system: false